/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  displayName?: LocalizedString;
  bio?: LocalizedText;
  services?: Array<
    {
      _key: string;
    } & LocalizedString
  >;
  recognition?: Array<
    {
      _key: string;
    } & LocalizedString
  >;
  publicContacts?: Array<{
    kind?: "email" | "phone" | "location";
    label?: LocalizedString;
    value?: string;
    href?: string;
    _type: "publicContact";
    _key: string;
  }>;
  socials?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  downloads?: Array<{
    kind?: "cv" | "portfolio";
    label?: LocalizedString;
    href?: string;
    _type: "downloadLink";
    _key: string;
  }>;
  canonicalBaseUrl?: string;
  seo?: Seo;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: LocalizedString;
  description?: LocalizedText;
  canonicalPath?: string;
  openGraphImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  twitterCard?: "summary_large_image" | "summary";
};

export type LocalizedString = {
  _type: "localizedString";
  en?: string;
  it?: string;
};

export type LocalizedText = {
  _type: "localizedText";
  en?: string;
  it?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  slug?: Slug;
  order?: number;
  client?: string;
  year?: number;
  service?: string;
  description?: LocalizedText;
  details?: ProjectDetails;
  credits?: Array<
    {
      _key: string;
    } & CreditGroup
  >;
  links?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  gallery?: Array<
    | ({
        _key: string;
      } & ImageMedia)
    | ({
        _key: string;
      } & VimeoMedia)
  >;
  seo?: Seo;
};

export type ProjectDetails = {
  _type: "projectDetails";
  context?: LocalizedText;
  challenge?: LocalizedText;
  solution?: LocalizedText;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type VimeoMedia = {
  _type: "vimeoMedia";
  url?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: LocalizedString;
  label?: LocalizedString;
};

export type ImageMedia = {
  _type: "imageMedia";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: LocalizedString;
  label?: LocalizedString;
};

export type ExternalLink = {
  _type: "externalLink";
  label?: LocalizedString;
  href?: string;
};

export type CreditGroup = {
  _type: "creditGroup";
  label?: LocalizedString;
  values?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SiteSettings
  | SanityImageAssetReference
  | Seo
  | LocalizedString
  | LocalizedText
  | Project
  | ProjectDetails
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | VimeoMedia
  | ImageMedia
  | ExternalLink
  | CreditGroup
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../antonio-salvatore-calo/src/cms/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(order asc){    _id,    title,    slug,    order,    client,    year,    service,    description,    details,    credits[]{_key, label, values},    links[]{_key, label, href},    seo{      title,      description,      canonicalPath,      "openGraphImage": openGraphImage.asset->url,      twitterCard    },    gallery[]{      _key,      _type,      alt,      label,      url,      image{        crop,        hotspot,        asset->{_id, url, metadata{dimensions}}      },      poster{        crop,        hotspot,        asset->{_id, url, metadata{dimensions}}      }    }  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: LocalizedString | null;
  slug: Slug | null;
  order: number | null;
  client: string | null;
  year: number | null;
  service: string | null;
  description: LocalizedText | null;
  details: ProjectDetails | null;
  credits: Array<{
    _key: string;
    label: LocalizedString | null;
    values: Array<string> | null;
  }> | null;
  links: Array<{
    _key: string;
    label: LocalizedString | null;
    href: string | null;
  }> | null;
  seo: {
    title: LocalizedString | null;
    description: LocalizedText | null;
    canonicalPath: string | null;
    openGraphImage: string | null;
    twitterCard: "summary_large_image" | "summary" | null;
  } | null;
  gallery: Array<
    | {
        _key: string;
        _type: "imageMedia";
        alt: LocalizedString | null;
        label: LocalizedString | null;
        url: null;
        image: {
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
        } | null;
        poster: null;
      }
    | {
        _key: string;
        _type: "vimeoMedia";
        alt: LocalizedString | null;
        label: LocalizedString | null;
        url: string | null;
        image: null;
        poster: {
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
        } | null;
      }
  > | null;
}>;

// Source: ../antonio-salvatore-calo/src/cms/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    displayName,    bio,    services,    recognition,    publicContacts[]{_key, kind, label, value, href},    socials[]{_key, label, href},    downloads[]{_key, kind, label, href},    canonicalBaseUrl,    seo{      title,      description,      canonicalPath,      "openGraphImage": openGraphImage.asset->url,      twitterCard    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  displayName: LocalizedString | null;
  bio: LocalizedText | null;
  services: Array<
    {
      _key: string;
    } & LocalizedString
  > | null;
  recognition: Array<
    {
      _key: string;
    } & LocalizedString
  > | null;
  publicContacts: Array<{
    _key: string;
    kind: "email" | "location" | "phone" | null;
    label: LocalizedString | null;
    value: string | null;
    href: string | null;
  }> | null;
  socials: Array<{
    _key: string;
    label: LocalizedString | null;
    href: string | null;
  }> | null;
  downloads: Array<{
    _key: string;
    kind: "cv" | "portfolio" | null;
    label: LocalizedString | null;
    href: string | null;
  }> | null;
  canonicalBaseUrl: string | null;
  seo: {
    title: LocalizedString | null;
    description: LocalizedText | null;
    canonicalPath: string | null;
    openGraphImage: string | null;
    twitterCard: "summary_large_image" | "summary" | null;
  } | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "project"] | order(order asc){\n    _id,\n    title,\n    slug,\n    order,\n    client,\n    year,\n    service,\n    description,\n    details,\n    credits[]{_key, label, values},\n    links[]{_key, label, href},\n    seo{\n      title,\n      description,\n      canonicalPath,\n      "openGraphImage": openGraphImage.asset->url,\n      twitterCard\n    },\n    gallery[]{\n      _key,\n      _type,\n      alt,\n      label,\n      url,\n      image{\n        crop,\n        hotspot,\n        asset->{_id, url, metadata{dimensions}}\n      },\n      poster{\n        crop,\n        hotspot,\n        asset->{_id, url, metadata{dimensions}}\n      }\n    }\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    displayName,\n    bio,\n    services,\n    recognition,\n    publicContacts[]{_key, kind, label, value, href},\n    socials[]{_key, label, href},\n    downloads[]{_key, kind, label, href},\n    canonicalBaseUrl,\n    seo{\n      title,\n      description,\n      canonicalPath,\n      "openGraphImage": openGraphImage.asset->url,\n      twitterCard\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
