#!/bin/sh
# =============================================================================
# Install Git Hooks — Antonio Salvatore Calò — Portfolio (Unix)
# =============================================================================
# Copies hooks from scripts/git-hooks/ to .git/hooks/ and makes them executable.
# Run this after cloning or when hooks are updated.
#
# Usage:
#   bash scripts/git-hooks/install.sh
#   npm run hooks:install
# =============================================================================

set -e

HOOKS_SRC="scripts/git-hooks"
HOOKS_DST=".git/hooks"

echo "── Installing git hooks ──────────────────────────────"

# Install pre-commit hook (generated by Node.js self-installer)
node "$HOOKS_SRC/pre-commit-check.mjs" --hook-install

# Preserve existing post-checkout and post-commit hooks (graphify)
for hook in post-checkout post-commit; do
    SRC="$HOOKS_SRC/$hook"
    DST="$HOOKS_DST/$hook"
    if [ -f "$SRC" ]; then
        cp "$SRC" "$DST"
        chmod +x "$DST"
        echo "  ✓ Installed: $hook"
    fi
done

echo "──────────────────────────────────────────────────────"
echo "  Hooks installed. To skip for a single commit:"
echo "    git commit --no-verify -m \"message\""
echo ""
